### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by seaprep** [purduesigbots/pros-atom3#25]
On MacOS after installing the MAC atoms package and MAC Client library from GitHub 3.10 release, the following errors occur when trying to create a new PROS project.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [pros-atom3](https://github.com/purduesigbots/pros-atom3) package 1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Applications/PROS Editor.app/Contents/Resources/app/node_modules/pathwatcher/lib/directory.js:361

TypeError: Cannot read property 'indexOf' of undefined
    at Directory.module.exports.Directory.isPathPrefixOf (/Applications/PROS Editor.app/Contents/Resources/app/node_modules/pathwatcher/lib/directory.js:361:29)
    at /packages/pros-atom3/lib/components/modals/NewProjectComponent.js:43:19)
    at /packages/pros-atom3/lib/views/NewProjectView.js:49:11)
    at newView (/packages/pros-atom3/lib/commands.js:13:7)
    at HTMLElement.didDispatch (/packages/pros-atom3/lib/commands.js:34:7)
    at CommandRegistry.handleCommandEvent (/Applications/PROS Editor.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/PROS Editor.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/PROS Editor.app/Contents/Resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (/Applications/PROS Editor.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:34.6.0 pros:new-project (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
file-icons 2.1.24 
ide-cquery 0.13.6 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
pros-atom3 1.0.1 
terminal-tab-plus 0.5.10 
tool-bar 1.1.10 
tool-bar-main 0.0.11 
```

**Comment by HotelCalifornia** [comment]
@seaprep when exactly did this error occur? was it when you clicked the 'New Project' menu option?

**Comment by seaprep** [comment]
Let me give you what I did:

1 - downloaded pros 3.10 MAC package (zip file)
2 - downloaded pros mac CLI package (zip file)

Move both to /Application directory

Then installed home-brew:

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Then did:  brew install cquery

All seemed fine.

Now when I start PROS and goto Create New Project - it asks all the right questions - give it a project name, pick V5 and latest kernel  Click Create Project and nothing happens I see no project created - I don’t see it i the file system etc.

If I do prosv5 conduct new prosv5-project01 in a terminal window the project is created etc.

Now when I open it in Atom, and lets say I open src/opcontrol.cpp I get a lot of ‘red dots’ indicating query errors as well, further more when I say go ahead and do “Build default” I get a bunch of errors as well — see below.


[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [pros-atom3](https://github.com/purduesigbots/pros-atom3) package 1.0.1


### Stack Trace

Uncaught ReferenceError: cmdopt is not defined

```
At /Users/willem/.pros-editor/packages/pros-atom3/lib/commands.js:62

ReferenceError: cmdopt is not defined
    at HTMLElement.didDispatch (/packages/pros-atom3/lib/commands.js:62:23)
    at CommandRegistry.handleCommandEvent (/Applications/PROS Editor.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/PROS Editor.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/PROS Editor.app/Contents/Resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (/Applications/PROS Editor.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -3:26.8.0 pros:new-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:04.6.0 pros:build-default (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0
busy 0.7.0
busy-signal 1.4.3
file-icons 2.1.24
ide-cquery 0.13.6
minimap 4.29.8
minimap-cursorline 0.2.0
minimap-find-and-replace 4.5.2
minimap-selection 4.5.0
pros-atom3 1.0.1
terminal-tab-plus 0.5.10
tool-bar 1.1.10
tool-bar-main 0.0.11
```

So I wonder if I missed something or otherwise screwed it up and this is not at all a PROS error, but a stupid user error on my part :)

Thanks for your help! Oh my Mac isa MacBook Air and basic vanilla nothing weird installed :)

Willem Scholten
Robotics Teacher and Coach
Seattle Preparatory School

wscholten@seaprep.org<mailto:wscholten@seaprep.org>
206.409.4168
www.seaprep.org<http://www.seaprep.org>


[cid:7465686F-EF4A-4F33-92E7-95F5235EB7C6@learningaccess.org]

On Sep 4, 2018, at 10:33 AM, Alex Brooke <notifications@github.com<mailto:notifications@github.com>> wrote:


@seaprep<https://github.com/seaprep> when exactly did this error occur? was it when you clicked the 'New Project' menu option?

**Comment by HotelCalifornia** [comment]
ah, okay. I see what the issue is now. It should be fixed in #22, which I have just published. Try updating the pros-atom3 package to version 1.0.3 and let me know if that fixes your issue.

**Comment by HotelCalifornia** [comment]
note that when using the PROS CLI.app, you may also need to run

```
ln -s /Applications/PROS\ CLI.app/Contents/MacOS/intercept-c* /usr/local/bin/
```
to put two executables used by PROS to generate the cquery metadata on the system PATH.

**Comment by HotelCalifornia** [comment]
final note: when you create a project from Terminal, you will need to run `prosv5 build-compile-commands` at least once to generate the cquery metadata

**Comment by seaprep** [comment]
That solves the query  problem, now have a new one…. when doing PROS -> Build -> Default it complaints about language variable setting and dies.

Also creating a new project from the PROS menu still does not work after the update.

Willem Scholten
Robotics Teacher and Coach
Seattle Preparatory School

wscholten@seaprep.org<mailto:wscholten@seaprep.org>
206.409.4168
www.seaprep.org<http://www.seaprep.org>


[cid:7465686F-EF4A-4F33-92E7-95F5235EB7C6@learningaccess.org]

On Sep 4, 2018, at 5:51 PM, Alex Brooke <notifications@github.com<mailto:notifications@github.com>> wrote:


final note: when you create a project from Terminal, you will need to run prosv5 build-compile-commands at least once to generate the cquery metadata

**Comment by HotelCalifornia** [comment]
Okay. There seem to be a few different issues here.

1) the language settings issue can be solved by opening the atom init script (File > Init Script), and adding the following two lines:
```js
process.env.LANG = 'en_US.utf-8'
process.env.LC_ALL = 'en_US.utf-8'
```
2) you say that creating a new project from the pros menu does not work (which was the original issue, I think). can you elaborate? does it show an error balloon? does it do nothing?

**Comment by HotelCalifornia** [comment]
follow-on from (2): are you still getting the error that you first mentioned in this issue?

**Comment by seaprep** [comment]
Language issue - yes this solves it and terminal opens and also build now runs as expected.

As to issue 2 - indeed when you click on PROS -> New Project, you get the initial pop-up, supply a project name, pick target V5 and kernel Latest and click Create Project - nothing happens, no errors balloon nothing - it does not create the project folder in the file system etc  I looked i the various logs but I see no errors being logged.  SO in short NO currently can not create a new project using PROS -> New Project button

Hope this helps, let me know what you would like me to try next.

Thanks.


On Sep 5, 2018, at 9:52 PM, Alex Brooke <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay. There seem to be a few different issues here.

  1.  the language settings issue can be solved by opening the atom init script (File > Init Script), and adding the following two lines:

process.env.LANG = 'en_US.utf-8'
process.env.LC_ALL = 'en_US.utf-8'

  1.  you say that creating a new project from the pros menu does not work (which was the original issue, I think). can you elaborate? does it show an error balloon? does it do nothing?

**Comment by HotelCalifornia** [comment]
Alright, thanks for your follow-up. When we merge #27, I'm going to close this issue because the original issue will have been fixed.

Would you mind adding your input about the inability to create projects to #24? It seems you're running into that same issue.
